version: '3'
networks:
  docker-strelo-net:

services:
  api:
    container_name: strelo-reward-api
    restart: always
    build: .
    ports:
      - "3333:3333"
    command: sh -c "npx prisma generate && npm run dev"
    environment:
      DATABASE_URL: "mongodb+srv://mongodbUser:PbVqC@JnLr7xkmw@reward-cluster.75fipx8.mongodb.net/streloreward?retryWrites=true&w=majority&appName=reward-cluster"

    volumes:
      - .:/app
      - /app/node_modules
